//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform_Project.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoo
    {
        public string TieuDe { get; set; }
        public string MaSoNhom { get; set; }
        public string MaDeTai { get; set; }
        public byte[] FileBaoCao { get; set; }
        public string TienDo { get; set; }
        public string NhanXet { get; set; }
        public string ThoiGianGui { get; set; }
        public string TrangThai { get; set; }
    }
}
