//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform_Project.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseContext : DbContext
    {
        public DatabaseContext()
            : base("name=DatabaseContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaoCaoo> BaoCaoos { get; set; }
        public virtual DbSet<GiangVienn> GiangVienns { get; set; }
        public virtual DbSet<Lichh> Lichhs { get; set; }
        public virtual DbSet<Messengerr> Messengerrs { get; set; }
        public virtual DbSet<NhiemVuu> NhiemVuus { get; set; }
        public virtual DbSet<SinhVienn> SinhVienns { get; set; }
        public virtual DbSet<ThongBaoo> ThongBaoos { get; set; }
        public virtual DbSet<ThongTinDangNhapp> ThongTinDangNhapps { get; set; }
        public virtual DbSet<ThongTinDeTaii> ThongTinDeTaiis { get; set; }
        public virtual DbSet<ThongTinNhomDangKyy> ThongTinNhomDangKyies { get; set; }
    }
}
