//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform_Project.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messengerr
    {
        public string NguoiGui { get; set; }
        public string NguoiNhan { get; set; }
        public string NoiDung { get; set; }
        public byte[] NoiDungDacBiet { get; set; }
        public System.DateTime ThoiGianGui { get; set; }
    }
}
