//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform_Project.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhiemVuu
    {
        public string TieuDe { get; set; }
        public Nullable<System.DateTime> ThoiGianGui { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public string TenNguoiNhan { get; set; }
        public string TenNguoiGui { get; set; }
        public string TrangThai { get; set; }
        public string NoiDung { get; set; }
        public string MSSV { get; set; }
        public string MaSoNhom { get; set; }
    }
}
