//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform_Project.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVienn
    {
        public string MSSV { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string SDT { get; set; }
        public string Khoa { get; set; }
        public string Nganh { get; set; }
        public string MaSoNhom { get; set; }
        public string Diem { get; set; }
    }
}
