//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winform_Project.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinNhomDangKyy
    {
        public string MSSV { get; set; }
        public string HoTen { get; set; }
        public string MaSoNhom { get; set; }
        public string MaDeTai { get; set; }
        public string TrangThai { get; set; }
    }
}
